const BASE="https://themosvagas.com.br";
const CITIES={PI:["Teresina","Parnaíba","Picos","Floriano","Piripiri","Campo Maior","União","Altos","José de Freitas","Pedro II","Oeiras","São Raimundo Nonato","Bom Jesus","Corrente","Esperantina"],MA:["São Luís","Imperatriz","Caxias","Timon","Codó","Bacabal","Balsas","Santa Inês"]};
const EMAIL=/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi;
const text=s=>(s||"").replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/gi," ").replace(/\s+/g," ").trim();
async function get(url){const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0 VagasEmailFinder"}});if(!r.ok)throw Error("HTTP "+r.status);return r.text()}
function links(html){const a=[],r=/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=r.exec(html))&&a.length<100){try{const u=new URL(m[1],BASE).href,t=text(m[2]);if(u.startsWith(BASE)&&t.length>5&&!u.includes("wp-content"))a.push({url:u,title:t})}catch{}}return a}
function date(html){const m=/<time[^>]+datetime=["']([^"']+)["']/i.exec(html);return m?new Date(m[1]).toISOString():null}
function emails(html){return[...new Set((text(html).replace(/\[at\]/gi,"@").replace(/\(at\)/gi,"@").match(EMAIL)||[]).map(x=>x.toLowerCase()))]}
function city(s){const l=s.toLocaleLowerCase("pt-BR");for(const [st,cs]of Object.entries(CITIES))for(const c of cs)if(l.includes(c.toLocaleLowerCase("pt-BR")))return{city:c,state:st};const m=s.match(/\b(PI|MA)\b/i);return{city:"",state:m?m[1].toUpperCase():""}}
function dateOk(d,f){if(f==="all")return true;if(!d)return false;const x=new Date(d),n=new Date(),z=new Date(n.getFullYear(),n.getMonth(),n.getDate());if(f==="today")return x>=z;if(f==="yesterday"){const y=new Date(z);y.setDate(y.getDate()-1);return x>=y&&x<z}const days=Number((f||"days:7").replace("days:","")),from=new Date(z);from.setDate(from.getDate()-days);return x>=from}
async function search(p){const q=(p.get("q")||"").trim(),st=(p.get("state")||"PI").toUpperCase(),cs=(p.get("cities")||"").split(",").filter(Boolean),f=p.get("days")||"today",targets=cs.length?cs:(CITIES[st]||[]),queries=q?targets.map(c=>q+" "+c):targets;const map=new Map();for(const v of queries.slice(0,25)){try{for(const x of links(await get(BASE+"/?s="+encodeURIComponent(v))))if(!map.has(x.url))map.set(x.url,x)}catch{}}const jobs=[];for(const x of [...map.values()].slice(0,24))try{const h=await get(x.url),t=text(h),l=city(t+" "+x.title),d=date(h);if(st&&l.state&&l.state!==st)continue;if(targets.length&&l.city&&!targets.includes(l.city))continue;if(!dateOk(d,f))continue;jobs.push({id:x.url,title:x.title,company:"",city:l.city,state:l.state,publishedAt:d,emails:emails(h),url:x.url})}catch{}const all=jobs.flatMap(x=>x.emails);return{jobs,stats:{total:jobs.length,withEmail:jobs.filter(x=>x.emails.length).length,withoutEmail:jobs.filter(x=>!x.emails.length).length,duplicates:all.length-new Set(all).size},searchedAt:new Date().toISOString()}}
const json=x=>new Response(JSON.stringify(x),{headers:{"content-type":"application/json","access-control-allow-origin":"*"}});
export default{async fetch(req,env){const u=new URL(req.url);if(u.pathname==="/api/health")return json({ok:true});if(u.pathname==="/api/search")try{return json(await search(u.searchParams))}catch(e){return json({error:e.message},502)}return env.ASSETS.fetch(req)}};